### ISSUE TITLE
Identify strategy for state management

### ISSUE THREAD

**Issue by bootstraponline** [software-platform/metrics#13]
Evaluate https://pub.dev/packages/states_rebuilder
- [States Rebuilder – ZERO Boilerplate Flutter State Management (video)](https://www.youtube.com/watch?v=iIxWMeFnIKA)
- [States Rebuilde (article)](https://resocoder.com/2019/12/30/states-rebuilder-zero-boilerplate-flutter-state-management/)
- https://github.com/ResoCoder/flutter-states-rebuilder-tutorial

Compare to [BLOC](https://pub.dev/packages/bloc) and [provider](https://pub.dev/packages/provider)

**Comment by illia-romanenko** [comment]
@bootstraponline is this still relevant?

**Comment by bootstraponline** [comment]
This is done. Thanks for flagging. State rebuilder seems to be working well so far.
