### ISSUE TITLE
Widget Theme support

### ISSUE THREAD

**Issue by bootstraponline** [software-platform/metrics#20]
A company should be able to change the theme so that colors in the app reflect the brand colors for that company.

**Comment by illia-romanenko** [comment]
Should this be as just using Flutter Theme or some custom Theme? Should also build some UI (or config) to configure that theme?

**Comment by bootstraponline** [comment]
Yeah I think yes custom theme plus also UI to configure the active theme. The goal is to change the colors only.

I have examples of two different themes here:

- https://github.com/software-platform/metrics/blob/master/docs/01_design_doc.md#minimal-viable-product
