### ISSUE TITLE
Review 3rd party API testing techniques

### ISSUE THREAD

**Issue by illia-romanenko** [software-platform/metrics#44]
As we integrate with 3rd party services like Jira & Slack we want to make sure that our integration is reliable.

As a result of this ticket completion, we want to have documented 3rd party API testing approach we plan to use for Jira & Slack integration testing.

**Comment by bootstraponline** [comment]
In Flank, I solved this by creating a mock server.
https://github.com/Flank/flank/blob/8861f7b9eb7ae46205326e8c4acf02e5331bd16c/test_runner/src/test/kotlin/ftl/test/util/MockServer.kt

That helps verify the API client is working as expected, without incurring the cost of talking to the real 3rd party service.

**Comment by vladlaba** [comment]
Hey @bootstraponline

I've analyzed different approaches in testing third party API today and reviewed one you mentioned ([MockServer](https://github.com/Flank/flank/blob/8861f7b9eb7ae46205326e8c4acf02e5331bd16c/test_runner/src/test/kotlin/ftl/test/util/MockServer.kt)) - please see this [document](https://docs.google.com/document/d/1emIkiAbZhjyybA89HwrxFqW04TkhNoMTSA2TJwbu5Sk/edit). It seems like the MockServer is a realization of fake service that consumes real HTTP requests (like 4th approach in document above). We can test our 3rd-party API integration using the same approach or combine it with others. Should we use any other methods?

**Comment by bootstraponline** [comment]
Nice work writing up the document for testing third party APIs! I think we should adopt the 4th approach, real HTTP requests to a mock server.

>  Should we use any other methods?

I think this is sufficient for API testing.
